source 'https://rubygems.org'

gem 'rails', '3.2.13'
gem 'sqlite3'
gem 'unicorn'
gem 'thin'
gem 'bootstrap-sass'
gem 'sorcery'
gem 'private_pub'
gem 'rails_autolink'
gem 'faraday'
gem 'vcr'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

group :development, :test do
  gem 'rspec-rails'
  gem 'capybara'
  gem 'capybara-webkit'
  gem 'launchy'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'simplecov'
end

gem 'jquery-rails'
